# Generated by Django 5.2 on 2025-05-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores/')),
                ('external_link', models.URLField(help_text='Link para WPP, iFood')),
                ('highlight', models.BooleanField(default=False)),
            ],
        ),
    ]
