# Generated by Django 5.2 on 2025-05-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='external_link',
        ),
        migrations.AddField(
            model_name='store',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='store',
            name='website_link',
            field=models.URLField(blank=True, null=True, verbose_name='Site Oficial'),
        ),
        migrations.AddField(
            model_name='store',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='store',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube'),
        ),
    ]
