# Generated by Django 4.2.23 on 2025-10-23 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='vitrine.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'shared_at'], name='vitrine_sha_store_i_1d9dea_idx')],
            },
        ),
    ]
