# Generated by Django 5.2 on 2025-05-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_remove_store_external_link_store_facebook_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
        migrations.AddField(
            model_name='store',
            name='carousel_2',
            field=models.ImageField(blank=True, null=True, upload_to='stores/carousel'),
        ),
        migrations.AddField(
            model_name='store',
            name='carousel_3',
            field=models.ImageField(blank=True, null=True, upload_to='stores/carousel'),
        ),
        migrations.AddField(
            model_name='store',
            name='carousel_4',
            field=models.ImageField(blank=True, null=True, upload_to='stores/carousel'),
        ),
        migrations.AddField(
            model_name='store',
            name='main_banner',
            field=models.ImageField(blank=True, null=True, upload_to='stores/banners'),
        ),
    ]
