# Generated by Django 4.2.23 on 2025-10-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_sharetrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWADownloadClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('clicked', 'Botão Clicado'), ('accepted', 'Instalação Aceita'), ('dismissed', 'Instalação Cancelada')], default='clicked', max_length=10)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PWA Download Click',
                'verbose_name_plural': 'PWA Download Clicks',
            },
        ),
    ]
