# Generated by Django 4.2.23 on 2025-10-27 04:08

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_pwadownloadclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sessão Ativa',
                'verbose_name_plural': 'Sessões Ativas',
                'indexes': [models.Index(fields=['last_activity'], name='vitrine_act_last_ac_caf56e_idx')],
            },
        ),
    ]
