# Generated by Django 5.2 on 2025-05-06 03:52

import vitrine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_remove_store_image_store_carousel_2_store_carousel_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='carousel_2',
            field=models.ImageField(blank=True, null=True, upload_to=vitrine.models.store_image_path),
        ),
        migrations.AlterField(
            model_name='store',
            name='carousel_3',
            field=models.ImageField(blank=True, null=True, upload_to=vitrine.models.store_image_path),
        ),
        migrations.AlterField(
            model_name='store',
            name='carousel_4',
            field=models.ImageField(blank=True, null=True, upload_to=vitrine.models.store_image_path),
        ),
        migrations.AlterField(
            model_name='store',
            name='main_banner',
            field=models.ImageField(blank=True, null=True, upload_to=vitrine.models.store_image_path),
        ),
    ]
