# Generated by Django 4.2.23 on 2026-02-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0004_activesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicktrack',
            name='element_type',
            field=models.CharField(choices=[('main_banner', 'Main Banner'), ('whatsapp_link_1', 'WhatsApp Link 1'), ('whatsapp_link_2', 'WhatsApp Link 2'), ('instagram_link', 'Instagram Link'), ('facebook_link', 'Facebook Link'), ('youtube_link', 'YouTube Link'), ('x_link', 'X Link'), ('google_maps_link', 'Google Maps Link'), ('anota_ai_link', 'Anota Ai Link'), ('ifood_link', 'iFood Link'), ('phone_link', 'Phone Link'), ('home_access', 'Home Access'), ('flyer_pdf', 'flyer PDF'), ('qr_code_scan', 'QR Code Scan')], max_length=50),
        ),
    ]
