# Generated by Django 4.2.23 on 2026-02-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0005_remove_click_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clicktrack',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='clicktrack',
            index=models.Index(fields=['store', 'element_type'], name='vitrine_cli_store_i_77733e_idx'),
        ),
    ]
