# Generated by Django 4.2.23 on 2026-03-13 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0006_remove_click_date2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTrackDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('main_banner', 'Main Banner'), ('whatsapp_link_1', 'WhatsApp Link 1'), ('whatsapp_link_2', 'WhatsApp Link 2'), ('instagram_link', 'Instagram Link'), ('facebook_link', 'Facebook Link'), ('youtube_link', 'YouTube Link'), ('x_link', 'X Link'), ('google_maps_link', 'Google Maps Link'), ('anota_ai_link', 'Anota Ai Link'), ('ifood_link', 'iFood Link'), ('phone_link', 'Phone Link'), ('home_access', 'Home Access'), ('flyer_pdf', 'flyer PDF'), ('qr_code_scan', 'QR Code Scan')], max_length=50)),
                ('date', models.DateField()),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicktrack_daily', to='vitrine.store')),
            ],
            options={
                'verbose_name': 'Clique Diário',
                'verbose_name_plural': 'Cliques Diários',
                'indexes': [models.Index(fields=['store', 'date'], name='vitrine_cli_store_i_0b34ae_idx'), models.Index(fields=['store', 'element_type', 'date'], name='vitrine_cli_store_i_3c3e5d_idx')],
                'unique_together': {('store', 'element_type', 'date')},
            },
        ),
    ]
