# Generated by Django 5.2 on 2025-05-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0006_tag_store_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='google_maps_link',
            field=models.URLField(blank=True, null=True, verbose_name='Google Maps'),
        ),
        migrations.AddField(
            model_name='store',
            name='x_link',
            field=models.URLField(blank=True, null=True, verbose_name='X'),
        ),
    ]
