# Generated by Django 4.2.23 on 2026-04-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0007_clicktrackdaily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeopeninghour',
            name='time_range',
        ),
        migrations.AddField(
            model_name='storeopeninghour',
            name='time_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeopeninghour',
            name='time_open',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='storeopeninghour',
            name='day_range',
            field=models.CharField(max_length=20),
        ),
    ]
