# Generated by Django 4.2.23 on 2026-05-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0008_remove_storeopeninghour_time_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verificada'),
        ),
        migrations.AddField(
            model_name='store',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verificada em'),
        ),
        migrations.CreateModel(
            name='StoreNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(choices=[('nova_loja', 'Nova Loja'), ('encarte', 'Encarte'), ('whatsapp_1', 'WhatsApp 1'), ('whatsapp_2', 'WhatsApp 2'), ('telefone', 'Telefone'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('x', 'X'), ('youtube', 'YouTube'), ('anota_ai', 'Anota Aí'), ('ifood', 'iFood'), ('google_maps', 'Google Maps'), ('endereco', 'Endereço')], max_length=20, verbose_name='Elemento')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('expira_em', models.DateTimeField(verbose_name='Expira em')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vitrine.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criada_em'],
                'indexes': [models.Index(fields=['store', 'elemento', 'criada_em'], name='vitrine_sto_store_i_0e88b0_idx'), models.Index(fields=['expira_em'], name='vitrine_sto_expira__8ac93a_idx')],
            },
        ),
    ]
