# Generated by Django 4.2.23 on 2026-06-22 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0009_store_is_verified_store_verified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1★'), (2, '2★'), (3, '3★'), (4, '4★'), (5, '5★')])),
                ('category', models.CharField(choices=[('suggestion', 'Sugestão'), ('praise', 'Elogio'), ('problem', 'Problema'), ('other', 'Outro')], max_length=20)),
                ('message', models.TextField(max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_spam', models.BooleanField(default=False)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='vitrine.activesession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='vitrine_fee_created_5e5640_idx'), models.Index(fields=['session', 'created_at'], name='vitrine_fee_session_1b9f3b_idx')],
            },
        ),
    ]
