# Generated by Django 5.2 on 2025-05-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0009_clicktrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicktrack',
            name='element_type',
            field=models.CharField(choices=[('main_banner', 'Main Banner'), ('carousel_2', 'Carousel 2'), ('carousel_3', 'Carousel 3'), ('carousel_4', 'Carousel 4'), ('whatsapp_link', 'WhatsApp Link'), ('instagram_link', 'Instagram Link'), ('facebook_link', 'Facebook Link'), ('youtube_link', 'YouTube Link'), ('x_link', 'X Link'), ('google_maps_link', 'Google Maps Link'), ('website_link', 'Website Link')], max_length=50),
        ),
    ]
