# Generated by Django 5.2 on 2025-05-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0010_alter_clicktrack_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicktrack',
            name='element_type',
            field=models.CharField(choices=[('main_banner', 'Main Banner'), ('whatsapp_link', 'WhatsApp Link'), ('instagram_link', 'Instagram Link'), ('facebook_link', 'Facebook Link'), ('youtube_link', 'YouTube Link'), ('x_link', 'X Link'), ('google_maps_link', 'Google Maps Link'), ('website_link', 'Website Link')], max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
    ]
