# Generated by Django 5.2 on 2025-06-10 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0015_alter_clicktrack_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicktrack',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicktrack', to='vitrine.store'),
        ),
    ]
