# Generated by Django 5.2 on 2025-06-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0016_alter_clicktrack_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
