# Generated by Django 5.2 on 2025-06-29 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0017_store_is_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='flyer_pdf',
            field=models.FileField(blank=True, null=True, upload_to='flyers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
