# Generated by Django 4.2.23 on 2025-08-15 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0019_alter_clicktrack_element_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_range', models.CharField(max_length=50)),
                ('time_range', models.CharField(max_length=50)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='vitrine.store')),
            ],
        ),
    ]
