# Generated by Django 4.2.23 on 2025-08-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0020_storeopeninghour'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
