# Generated by Django 4.2.23 on 2025-08-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0021_store_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='whatsapp_link',
        ),
        migrations.AddField(
            model_name='store',
            name='phone_link',
            field=models.URLField(blank=True, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='store',
            name='whatsapp_link_1',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp_1'),
        ),
        migrations.AddField(
            model_name='store',
            name='whatsapp_link_2',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp_2'),
        ),
    ]
