# Generated by Django 4.2.23 on 2025-08-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0022_remove_store_whatsapp_link_store_phone_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone_link',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
