# Generated by Django 4.2.23 on 2025-08-20 02:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0023_alter_store_phone_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='qr_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
