# Generated by Django 4.2.23 on 2025-08-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0025_alter_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
