# Generated by Django 4.2.23 on 2025-08-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0026_alter_store_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
